### PR TITLE
Incorrect text used to search for session id.

### PR DESCRIPTION
**Pull request by doychin**
Session ID: 10
  name:  powerpro
  user:  SYSDBA
  date:  2016-06-03 18:24:47
  flags: active, admin, trace

Session ID: 11
  name:  powerpro
  user:  SYSDBA
  date:  2016-06-03 22:59:09
  flags: active, admin, trace

### CODE REVIEW

**Comment by mrotteveel** [comment]
Could you describe the problem is this pull request solves? I don't really use trace, but as far as I know, Firebird 2.5 uses `"Trace session ID "` (eg see http://www.firebirdsql.org/rlsnotesh/rlsnotes25.html#rnfb25-trace); if Firebird 3 changed that, then this needs to be solved in a backwards compatible manner.

**Comment by mrotteveel** [comment]
I just checked Firebird 2.5.5 and Firebird 3.0, and both report 'Trace session ID n started`.

**Comment by doychin** [comment]
Then I think it will be good idea to add also parsing for trace_list. This way in case there is nothing else generated trace manger will know the active sessions.

**Comment by mrotteveel** [comment]
The trace supports in Jaybird is rather rudimentary. I was considering reimplementing it in a future Jaybird version, but I'm not sure if I can find the time to do that. Pull requests are always welcome though :).

**Comment by doychin** [comment]
On 4.6.2016 г. 17:18 ч., Mark Rotteveel wrote:
> The trace supports in Jaybird is rather rudimentary. I was considering
> reimplementing it in a future Jaybird version, but I'm not sure if I can
> find the time to do that. Pull requests are always welcome though :).
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/FirebirdSQL/jaybird/pull/13#issuecomment-223758100>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGzQk8yI_QnnIxCwyCkBd1wR-PhUwKI5ks5qIYk1gaJpZM4It3FR>.
>

I will try to implement better support for trace functionality.
I think it is essential to have the ability to trace problems in a 
production environment without having to relay on external tools.

In my case I need to track all statements for live transactions and keep 
them in memory for reference until transaction is closed.

I have one problem where a transaction blocks the execution of other 
transactions and I can't find what statements were executed in this 
transaction.

It is an EJB 2 application and sometimes this remains unnoticed for long 
time. After I find about the problem and restart the application, it 
gets into sweep nightmare for few hours until all garbage is removed.

My idea is to add trace support inside the application and be able to 
track different cases including long running statements.

-- 
Doychin Bondzhev
dSoft-Bulgaria Ltd.
PowerPro - billing & provisioning solution for Service providers
PowerStor - Warehouse & POS
http://www.dsoft-bg.com/
Mobile: +359888243116

**Pull request closed without merging**
