### PR TITLE
Fix USHORT->short->int conversion when reading varchars

### PR DESCRIPTION
**Pull request by artyom-smirnov**
This fixed reading strings > 255 chars.

### CODE REVIEW

**Comment by mrotteveel** [comment]
Thanks, that is a curious mistake, and strange that it hasn't surfaced earlier.

May I suggest that you use branches for future pull-requests, that will prevent your master from diverging from the main repository if something is committed between your change and me merging it.

**Comment by artyom-smirnov** [comment]
Yes, do not know why I've committed to my master, its better to create topic branch of course.

**Comment by mrotteveel** [comment]
Tracker ticket: http://tracker.firebirdsql.org/browse/JDBC-518

**Comment by mrotteveel** [comment]
Thanks for reporting and the fix. I'll add some tests with longer strings to catch regressions on this in the future.

**Comment by artyom-smirnov** [comment]
You are welcome!

**Pull request merged**
