### PR TITLE
Fix USHORT->short->int conversion when reading varchars

### PR DESCRIPTION
**Pull request by artyom-smirnov**
This fixed reading strings > 255 chars.

### CODE REVIEW

**Comment by mrotteveel** [comment]
Did you accidentally submit this twice? It seems to be identical to #17

**Comment by artyom-smirnov** [comment]
This one is for 3.0 branch. Same problem.

**Comment by mrotteveel** [comment]
Ah sorry, hadn't noticed that.

**Comment by mrotteveel** [comment]
Tracker ticket: http://tracker.firebirdsql.org/browse/JDBC-518

**Pull request merged**
