### PR TITLE
JDBC-509: upgrade to JNA 5.2.0

### PR DESCRIPTION
**Pull request by serval2412**

### CODE REVIEW

**Comment by mrotteveel** [comment]
Thanks. I'll test this later this week, and consider if I'll merge it.

My original plan was to only update this dependency when Jaybird 4 was nearly release-ready to avoid having to update multiple times (or risk releasing with an outdated version). On the other hand, this may provide an opportunity to verify if there are no problems going from 4 to 5.

**Comment by serval2412** [comment]
Thank you for your feedback.
I must recognize I didn't test the patch, I thought there was an automatic mechanism to test the patch (Jenkins like).
Also, I didn't build the jar but retrieved a build so can't tell which glibc version it uses.
So I'd understand you'd close this one without pushing it.

**Comment by mrotteveel** [comment]
The lack of CI is something that I want to fix at some point, but some tests require to have Firebird running locally which complicates things a bit, although maybe as a start I could try to add a CI config that at least compiles.

In any case, I'll check out and run the tests locally. There were some breaking changes between JNA 4.4 and 5, but I'm not sure if the current use in Jaybird will be affected.

**Comment by asfernandes** [comment]
node-firebird-drivers installs Firebird in travis and appveyor. See:
- https://github.com/asfernandes/node-firebird-drivers/blob/master/.travis.yml
- https://github.com/asfernandes/node-firebird-drivers/blob/master/appveyor.yml

**Comment by mrotteveel** [comment]
@asfernandes Thanks, I'll see if that works for Jaybird as well.

**Comment by mrotteveel** [comment]
It compiles. There is a deprecation notice for `Platform.loadLibrary` as `Platform.load` was added to provide better compile time checks. That is fine to leave as is for now.

A problem is that the embedded tests hang (Java 7 and 8 + Firebird 3; Java 11 seems to work), where the same tests with JNA 4.4 works just fine. I'll need to dig into that some more.

**Comment by serval2412** [comment]
Thank you for the update!
BTW, creating this patch was quite quick to make (git rm <old version> git add <new version> + update version in some files) so don't worry for the update. Don't hesitate to ping me to do it if there is  a new version when  you'll have fixed the pbs of this patch and pushed it.

**Comment by mrotteveel** [comment]
Thanks, will do that.

**Comment by mrotteveel** [comment]
As another datapoint, the problem also occurs with Java 11 when the code has been compiled with Java 8. The problem seems to occur during exit of the Java process that ran the test (specifically `org.firebirdsql.jdbc.FBConnectionTest`. JVisualVM no longer shows the test process, but it is present in the taskmanager, which could indicate this is related to JDBC-519 (or at least to problems unloading the embedded library).

**Comment by mrotteveel** [comment]
Ignoring test `org.firebirdsql.jdbc.FBConnectionTest.testLockTable` seems to resolve the issue (although ant still seems to hang quite some time on this test class). It seems like table locks lead to problems with the connection, which in turn result in issues with unloading the library.

**Comment by mrotteveel** [comment]
I added a workaround to FBConnectionTest to explicitly shutdown embedded after tests which provides a stopgap solution for the problem. Created JDBC-575 to find out if there is an underlying problem (dangling connection, statement or transaction), or otherwise provide a more general solution to call fb_shutdown after tests.

I have merge this pull request. Thanks for your contribution!

**Pull request merged**
